"""<your_message>

Revision ID: 42e5c0a76ffa
Revises: df8e6b5e1bc9
Create Date: 2025-04-23 18:07:58.268441

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42e5c0a76ffa"
down_revision = "df8e6b5e1bc9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_cache",
        sa.Column("hash_id", sa.String(length=255), nullable=False),
        sa.Column("pdf_url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("hash_id", name=op.f("pk_image_cache")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image_cache")
    # ### end Alembic commands ###
