"""<your_message>

Revision ID: 32b515705809
Revises: 42e5c0a76ffa
Create Date: 2025-04-23 18:31:13.171152

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32b515705809"
down_revision = "42e5c0a76ffa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation_cache",
        sa.Column("translation_encode", sa.String(length=255), nullable=False),
        sa.Column("pdf_url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint(
            "translation_encode", name=op.f("pk_translation_cache")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translation_cache")
    # ### end Alembic commands ###
