version: '3.8'
services:
    gateway_service:
        image: sa-backend-gateway
        build:
            context: ./gateway_service
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        env_file:
            - ./gateway_service/.env
        networks:
            - sa_cs2
        volumes:
            - storage:/storage
        depends_on:
            rabbitmq:
                condition: service_healthy
            mysql:
                condition: service_healthy

    ocr_service:
        image: sa-backend-ocr
        build:
            context: ./ocr_service
            dockerfile: Dockerfile
        ports:
            - "5001:5001"
        env_file:
            -   ./ocr_service/.env
        networks:
            - sa_cs2
        volumes:
            - storage:/storage
        depends_on:
            rabbitmq:
                condition: service_healthy
            mysql:
                condition: service_healthy

    pdf_service:
        image: sa-backend-pdf
        build:
            context: ./pdf_service
            dockerfile: Dockerfile
        ports:
            - "5002:5002"
        env_file:
            - ./pdf_service/.env
        networks:
            - sa_cs2
        volumes:
            - storage:/storage
        depends_on:
            rabbitmq:
                condition: service_healthy
            mysql:
                condition: service_healthy

    translation_service:
        image: sa-backend-translate
        build:
            context: ./translation_service
            dockerfile: Dockerfile
        ports:
            - "5003:5003"
        env_file:
            - ./translation_service/.env
        networks:
            - sa_cs2
        depends_on:
            rabbitmq:
                condition: service_healthy

    rabbitmq:
        image: rabbitmq:4.0.8-management
        networks:
            - sa_cs2
        command: bash -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_PLUGINS: "rabbitmq_management"
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3

    redis:
        image: redis:7.4.2
        networks:
            - sa_cs2
        ports:
            - 6379:6379
        volumes:
            - sa_cs2-redis:/data

    mysql:
        image: mysql:8.0.32
        env_file:
            -   ./gateway_service/.env
        ports:
            - 3308:3306
        networks:
            - sa_cs2
        volumes:
            - sa_cs2-value:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    sa_cs2-redis:
        driver: local

    storage:
    sa_cs2-value:

networks:
    sa_cs2:


