version: '3.8'
services:
    backend:
        image: sa-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        env_file:
            -   .env
